pluginGroup = com.github.mikusr.catppuccin.latte.warm
pluginName = Catppuccin Latte Warm
pluginVersion = 1.0.0
pluginSinceBuild = 231
pluginUntilBuild = 262.*
platformType = IC
platformVersion = 2025.2.1
platformPlugins =
javaVersion = 21
gradleVersion = 9.6.1
kotlin.stdlib.default.dependency = false
org.gradle.configuration-cache = true
